const ACUTE = 'ACUTE';
const RIGHT = 'RIGHT';
const OBTUSE = 'OBTUSE';
const SCALENE = 'SCALENE';
const ISOSCELES = 'ISOSCELES';
const EQUILATERAL = 'EQUILATERAL';

module.exports = {
    ACUTE, OBTUSE, RIGHT, SCALENE, ISOSCELES, EQUILATERAL,
};